### ISSUE TITLE
3 gradio issues

### ISSUE THREAD

**Issue by lucyknada** [dvlab-research/MiniGemini#13]
There's quite a few gradio issues:

1. function_markdown is undefined
2. unexpected keyword concurrency_limit
3. recursive json encoder

First two were "fixed" by just commenting them out, however the third issue prevent gradio working at all as it immediately crashes the instance with that error.

```
/xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
  chatbot = gr.Chatbot(
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/xxx/minigemini/serve/gradio_web_server.py", line 472, in <module>
    demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
  File "/xxx/minigemini/serve/gradio_web_server.py", line 371, in build_demo
    gr.Markdown(function_markdown)
```

```
/xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
  chatbot = gr.Chatbot(
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/xxx//minigemini/serve/gradio_web_server.py", line 472, in <module>
    demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
  File "/xxx//minigemini/serve/gradio_web_server.py", line 394, in build_demo
    regenerate_btn.click(
TypeError: EventListenerMethod.__call__() got an unexpected keyword argument 'concurrency_limit'
```

```
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
  encoded_value = jsonable_encoder(
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
  return jsonable_encoder(
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
  encoded_value = jsonable_encoder(
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
  return jsonable_encoder(
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
  encoded_value = jsonable_encoder(
File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
  if isinstance(obj, classes_tuple):
File "/usr/lib64/python3.10/abc.py", line 119, in __instancecheck__
  return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by lightingvector** [comment]
update please ?

**Comment by lightingvector** [comment]
uncomment concurrency_limit and upgrade gradio and it should work just fine.
however im running into NameError: name 'PaddleOCR' is not defined, while made sure to install paddleocr as documented:
`python3 -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple`

**Comment by yanwei-li** [comment]
Hi, it is optional to install `PaddleOCR` for better OCR experience, but it is not a necessary option.
If you want to install it, I guess you need to first installed [PaddlePaddle](https://www.paddlepaddle.org.cn/en) and then install [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). It is not so easy to install in some cases (at least for me). Of course, you can also choose another ocr detector for replacement with simple modification in the code.

**Comment by WhiteWolf21** [comment]
> There's quite a few gradio issues:
> 
> 1. function_markdown is undefined
> 2. unexpected keyword concurrency_limit
> 3. recursive json encoder
> 
> First two were "fixed" by just commenting them out, however the third issue prevent gradio working at all as it immediately crashes the instance with that error.
> 
> ```
> /xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
>   chatbot = gr.Chatbot(
> Traceback (most recent call last):
>   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/xxx/minigemini/serve/gradio_web_server.py", line 472, in <module>
>     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
>   File "/xxx/minigemini/serve/gradio_web_server.py", line 371, in build_demo
>     gr.Markdown(function_markdown)
> ```
> 
> ```
> /xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
>   chatbot = gr.Chatbot(
> Traceback (most recent call last):
>   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/xxx//minigemini/serve/gradio_web_server.py", line 472, in <module>
>     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
>   File "/xxx//minigemini/serve/gradio_web_server.py", line 394, in build_demo
>     regenerate_btn.click(
> TypeError: EventListenerMethod.__call__() got an unexpected keyword argument 'concurrency_limit'
> ```
> 
> ```
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
>   encoded_value = jsonable_encoder(
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
>   return jsonable_encoder(
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
>   encoded_value = jsonable_encoder(
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
>   return jsonable_encoder(
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
>   encoded_value = jsonable_encoder(
> File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
>   if isinstance(obj, classes_tuple):
> File "/usr/lib64/python3.10/abc.py", line 119, in __instancecheck__
>   return _abc_instancecheck(cls, instance)
> RecursionError: maximum recursion depth exceeded in comparison
> ```

I can be able to run by modify the gradio version and apply the latest one (4.24.0), which now the web server is running normally and the upload file component look the same as the repo demo. I think this maybe the solution for the third issue and you can try.

![image](https://github.com/dvlab-research/MiniGemini/assets/31312589/7f7dd622-b2f2-475e-baf7-cf85f70cb04d)

**Comment by gw00259532** [comment]
> > There's quite a few gradio issues:
> > 
> > 1. function_markdown is undefined
> > 2. unexpected keyword concurrency_limit
> > 3. recursive json encoder
> > 
> > First two were "fixed" by just commenting them out, however the third issue prevent gradio working at all as it immediately crashes the instance with that error.
> > ```
> > /xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
> >   chatbot = gr.Chatbot(
> > Traceback (most recent call last):
> >   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
> >     exec(code, run_globals)
> >   File "/xxx/minigemini/serve/gradio_web_server.py", line 472, in <module>
> >     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
> >   File "/xxx/minigemini/serve/gradio_web_server.py", line 371, in build_demo
> >     gr.Markdown(function_markdown)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > /xxx//minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
> >   chatbot = gr.Chatbot(
> > Traceback (most recent call last):
> >   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
> >     exec(code, run_globals)
> >   File "/xxx//minigemini/serve/gradio_web_server.py", line 472, in <module>
> >     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
> >   File "/xxx//minigemini/serve/gradio_web_server.py", line 394, in build_demo
> >     regenerate_btn.click(
> > TypeError: EventListenerMethod.__call__() got an unexpected keyword argument 'concurrency_limit'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
> >   encoded_value = jsonable_encoder(
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
> >   return jsonable_encoder(
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
> >   encoded_value = jsonable_encoder(
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
> >   return jsonable_encoder(
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
> >   encoded_value = jsonable_encoder(
> > File "/xxx//venv/lib64/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
> >   if isinstance(obj, classes_tuple):
> > File "/usr/lib64/python3.10/abc.py", line 119, in __instancecheck__
> >   return _abc_instancecheck(cls, instance)
> > RecursionError: maximum recursion depth exceeded in comparison
> > ```
> 
> I can be able to run by modify the gradio version and apply the latest one (4.24.0), which now the web server is running normally and the upload file component look the same as the repo demo. I think this maybe the solution for the third issue and you can try.
> 
> ![image](https://private-user-images.githubusercontent.com/31312589/318774821-6221bbbc-15e1-44d0-ba67-e0c0b13e153b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDg0MjcsIm5iZiI6MTcxMzQwODEyNywicGF0aCI6Ii8zMTMxMjU4OS8zMTg3NzQ4MjEtNjIyMWJiYmMtMTVlMS00NGQwLWJhNjctZTBjMGIxM2UxNTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAyNDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTQyMzBjYmY1YmRjNGYxZjViNjU4ZmY5ZDNhNjllMzc4ODY3ZTlmZDAyN2QxZDllNzJlZTM5YjI1YmFiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VxJv8ccgE3b0-kmkHePe0JpiyqmeaRhtucdA4NiXhCk)

This solution does not work for me...

**Comment by WhiteWolf21** [comment]
@gw00259532 Please share the problem you are encoutering, I can have a look and help 👍

**Comment by gw00259532** [comment]
> @gw00259532 Please share the problem you are encoutering, I can have a look and help 👍

Hi, thanks for your help~
I encountered the same problem as described by @lucyknada. The gradio==4.24.0 was installed but the "function_markdown is undefined" error was still exist

**Comment by gw00259532** [comment]
> @gw00259532 Please share the problem you are encoutering, I can have a look and help 👍

Here are logs
`[2024-04-18 10:51:32,529] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/yenianjin/anaconda3/envs/Alpaca/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
New model not imported. Try to update Transformers to 4.38.0 or later.
2024-04-18 10:51:37 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-18 10:51:37 | INFO | gradio_web_server | Models: []
2024-04-18 10:51:37 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-18 10:51:37 | ERROR | stderr | /mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
2024-04-18 10:51:37 | ERROR | stderr |   chatbot = gr.Chatbot(
2024-04-18 10:51:37 | ERROR | stderr | Traceback (most recent call last):
2024-04-18 10:51:37 | ERROR | stderr |   File "/home/yenianjin/anaconda3/envs/Alpaca/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-04-18 10:51:37 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-18 10:51:37 | ERROR | stderr |   File "/home/yenianjin/anaconda3/envs/Alpaca/lib/python3.10/runpy.py", line 86, in _run_code
2024-04-18 10:51:37 | ERROR | stderr |     exec(code, run_globals)
2024-04-18 10:51:37 | ERROR | stderr |   File "/mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py", line 472, in <module>
2024-04-18 10:51:37 | ERROR | stderr |     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
2024-04-18 10:51:37 | ERROR | stderr |   File "/mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py", line 371, in build_demo
2024-04-18 10:51:37 | ERROR | stderr |     gr.Markdown(function_markdown)
2024-04-18 10:51:37 | ERROR | stderr | NameError: name 'function_markdown' is not defined`

**Comment by gw00259532** [comment]
Here are logs @WhiteWolf21 
```
2024-04-18 10:51:37 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-18 10:51:37 | INFO | gradio_web_server | Models: []
2024-04-18 10:51:37 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-18 10:51:37 | ERROR | stderr | /mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
2024-04-18 10:51:37 | ERROR | stderr |   chatbot = gr.Chatbot(
2024-04-18 10:51:37 | ERROR | stderr | Traceback (most recent call last):
2024-04-18 10:51:37 | ERROR | stderr |   File "/home/yenianjin/anaconda3/envs/Alpaca/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-04-18 10:51:37 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-18 10:51:37 | ERROR | stderr |   File "/home/yenianjin/anaconda3/envs/Alpaca/lib/python3.10/runpy.py", line 86, in _run_code
2024-04-18 10:51:37 | ERROR | stderr |     exec(code, run_globals)
2024-04-18 10:51:37 | ERROR | stderr |   File "/mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py", line 472, in <module>
2024-04-18 10:51:37 | ERROR | stderr |     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
2024-04-18 10:51:37 | ERROR | stderr |   File "/mnt/ws-data/data/project/MiniGemini/minigemini/serve/gradio_web_server.py", line 371, in build_demo
2024-04-18 10:51:37 | ERROR | stderr |     gr.Markdown(function_markdown)
2024-04-18 10:51:37 | ERROR | stderr | NameError: name 'function_markdown' is not defined
```

**Comment by WhiteWolf21** [comment]
@gw00259532 please uncomment like in the image:
![image](https://github.com/dvlab-research/MiniGemini/assets/31312589/86641f97-22f0-4cc2-94c5-52b86c681608)

**Comment by gw00259532** [comment]
> @gw00259532 please uncomment like in the image: ![image](https://private-user-images.githubusercontent.com/31312589/323455300-86641f97-22f0-4cc2-94c5-52b86c681608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTEwNjMsIm5iZiI6MTcxMzQxMDc2MywicGF0aCI6Ii8zMTMxMjU4OS8zMjM0NTUzMDAtODY2NDFmOTctMjJmMC00Y2MyLTk0YzUtNTJiODZjNjgxNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAzMjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODlhNDVlYzI4OWE5YzY4YzIwNDg1OGE3ZDUyN2JkZmQwMGE3NzdhY2NmYzM4ZDRlNDRkOTA1MjJmY2ZlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.25cX1xJz2CpSC3QxxV6a-vW-8IQmMe7aCjN-XE5a74E)

I comment the lines `gr.Markdown(function_markdown)` and `concurrency_limit=concurrency_count` can fix the first two problems.   Thanks a lot!
