### ISSUE TITLE
minigemini.model.multimodal_encoder.openclip_encoder.CLIP() got NoneType

### ISSUE THREAD

**Issue by SuSung-boy** [dvlab-research/MiniGemini#55]
I got this !

Traceback (most recent call last):
  File "~/miniconda3/envs/mnig/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/miniconda3/envs/mnig/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~/MiniGemini/minigemini/serve/cli.py", line 237, in <module>
    main(args)
  File "~/MiniGemini/minigemini/serve/cli.py", line 56, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "~/MiniGemini/minigemini/model/builder.py", line 119, in load_pretrained_model
    vision_tower_aux.load_model()
  File "~/MiniGemini/minigemini/model/multimodal_encoder/openclip_encoder.py", line 40, in load_model
    clip_model = CLIP(**get_model_config(self.model_type))
TypeError: minigemini.model.multimodal_encoder.openclip_encoder.CLIP() argument after ** must be a mapping, not NoneType

but I try debug this func 'get_model_config', it take any model_type of (['convnext_large_d_320', 'convnext_base_w_320', 'convnext_xxlarge']), and always return None.

how this happen and how can I fix this?

**Comment by SuSung-boy** [comment]
forget it
I fix this by upgrade open_clip repo version 
! pip install open-clip-torch -U
