### ISSUE TITLE
Deployed mini-Gemini in the Windows system and encountered the following error during the ”Launch a Graph web server“ step. seeking help from a skilled user to resolve the issue

### ISSUE THREAD

**Issue by Janusmsr** [dvlab-research/MiniGemini#81]
(minigemini) PS G:\MiniGemini> python -m minigemini.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
D:\Anaconda3\envs\minigemini\lib\site-packages\transformers\utils\generic.py:485: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\Anaconda3\envs\minigemini\lib\site-packages\transformers\utils\generic.py:342: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\Anaconda3\envs\minigemini\lib\site-packages\transformers\utils\generic.py:342: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\Anaconda3\envs\minigemini\lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
2024-04-21 18:15:58 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-21 18:16:02 | INFO | gradio_web_server | Models: []
2024-04-21 18:16:02 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-04-21 18:16:03 | ERROR | stderr | G:\MiniGemini\minigemini\serve\gradio_web_server.py:351: UserWarning: `layout` parameter is deprecated, and it has no effect
2024-04-21 18:16:03 | ERROR | stderr |   chatbot = gr.Chatbot(
2024-04-21 18:16:03 | ERROR | stderr | Traceback (most recent call last):
2024-04-21 18:16:03 | ERROR | stderr |   File "D:\Anaconda3\envs\minigemini\lib\runpy.py", line 196, in _run_module_as_main
2024-04-21 18:16:03 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-21 18:16:03 | ERROR | stderr |   File "D:\Anaconda3\envs\minigemini\lib\runpy.py", line 86, in _run_code
2024-04-21 18:16:03 | ERROR | stderr |     exec(code, run_globals)
2024-04-21 18:16:03 | ERROR | stderr |   File "G:\MiniGemini\minigemini\serve\gradio_web_server.py", line 472, in <module>
2024-04-21 18:16:03 | ERROR | stderr |     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
2024-04-21 18:16:03 | ERROR | stderr |   File "G:\MiniGemini\minigemini\serve\gradio_web_server.py", line 371, in build_demo
2024-04-21 18:16:03 | ERROR | stderr |     gr.Markdown(function_markdown)
2024-04-21 18:16:03 | ERROR | stderr | NameError: name 'function_markdown' is not defined

**Comment by Adenialzz** [comment]
how do you solve this ?
